spring:
   output:
      ansi:
       enabled: DETECT     
   
logging:
  file: ../logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.cts.pm: DEBUG
    org.hibernate: ERROR   
    
